<?php
/**
 * Copyright (c) 2016 CTI Digital
 * Copyright (c) 2026 Magebit, Ltd.
 *
 * Licensed under the MIT License; see the LICENSE file in the project root.
 */

declare(strict_types=1);

namespace Magebit\Configurator\Test\Unit\Component;

use Magebit\Configurator\Api\ComponentMode;
use Magebit\Configurator\Api\LoggerInterface;
use Magebit\Configurator\Api\VersionManagementInterface;
use Magebit\Configurator\Component\Rewrites;
use Magebit\Configurator\Model\ComponentContext;
use Magebit\Configurator\Model\ComponentResult;
use Magebit\Configurator\Model\Export\ExportContext;
use Magebit\Configurator\Model\Reconciliation\ReconciliationGate;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollection as Collection;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewrite as UrlRewriteResource;
use Magento\UrlRewrite\Model\UrlRewrite;
use Magento\UrlRewrite\Model\UrlRewriteFactory;
use Magento\UrlRewrite\Model\UrlPersistInterface;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class RewritesTest extends TestCase
{
    private UrlPersistInterface&MockObject $urlPersist;
    private UrlRewriteFactory&MockObject $urlRewriteFactory;
    private UrlRewriteResource&MockObject $urlRewriteResource;
    private LoggerInterface&MockObject $log;
    private Rewrites $component;

    protected function setUp(): void
    {
        $this->urlPersist = $this->createMock(UrlPersistInterface::class);
        $this->urlRewriteFactory = $this->getMockBuilder(UrlRewriteFactory::class)
            ->disableOriginalConstructor()
            ->onlyMethods(['create'])
            ->getMock();
        $this->urlRewriteResource = $this->createMock(UrlRewriteResource::class);
        $this->log = $this->createMock(LoggerInterface::class);

        // Real gate over a version store that always reports "not newer".
        $versionManagement = $this->createMock(VersionManagementInterface::class);
        $versionManagement->method('isNewVersion')->willReturn(false);
        $gate = new ReconciliationGate($versionManagement, $this->log);

        $this->component = new Rewrites(
            $this->urlPersist,
            $this->urlRewriteFactory,
            $this->urlRewriteResource,
            $this->log,
            $gate
        );
    }

    public function testCreatesRewriteWhenItDoesNotExist(): void
    {
        // No existing rewrite (collection size 0) -> create path.
        $rewrite = $this->givenRewriteWithCollection(0);
        $rewrite->method('setIsAutogenerated')->willReturnSelf();
        $rewrite->method('setStoreId')->willReturnSelf();
        $rewrite->method('setRequestPath')->willReturnSelf();
        $rewrite->method('setTargetPath')->willReturnSelf();
        $rewrite->method('setRedirectType')->willReturnSelf();
        $rewrite->method('setDescription')->willReturnSelf();
        $this->urlRewriteFactory->method('create')->willReturn($rewrite);

        $this->urlRewriteResource->expects($this->once())->method('save')->with($rewrite);

        $result = $this->execute($this->sampleSource());

        $this->assertTrue($result->isSuccessful());
        $this->assertSame(1, $result->getCreated());
        $this->assertSame(0, $result->getUpdated());
    }

    public function testCreateModeProtectsExistingRewrite(): void
    {
        // Collection size 1 -> entity exists; create mode with no version bump -> skip.
        $rewrite = $this->givenRewriteWithCollection(1);
        $this->urlRewriteFactory->method('create')->willReturn($rewrite);

        $this->urlRewriteResource->expects($this->never())->method('save');

        $result = $this->execute($this->sampleSource());

        $this->assertSame(0, $result->getCreated());
        $this->assertSame(1, $result->getSkipped());
        $this->assertTrue($result->isSuccessful());
    }

    public function testMaintainModeUpdatesExistingRewrite(): void
    {
        // Existing rewrite; maintain mode -> update path, loads first item and saves it.
        $existing = $this->makeUrlRewriteMock($this->setterMethods());
        $existing->method('setIsAutogenerated')->willReturnSelf();
        $existing->method('setStoreId')->willReturnSelf();
        $existing->method('setRequestPath')->willReturnSelf();
        $existing->method('setTargetPath')->willReturnSelf();
        $existing->method('setRedirectType')->willReturnSelf();
        $existing->method('setDescription')->willReturnSelf();

        $rewrite = $this->givenRewriteWithCollection(1, $existing);
        $this->urlRewriteFactory->method('create')->willReturn($rewrite);

        $this->urlRewriteResource->expects($this->once())->method('save')->with($existing);

        $result = $this->execute($this->sampleSource(), false, ComponentMode::Maintain);

        $this->assertSame(0, $result->getCreated());
        $this->assertSame(1, $result->getUpdated());
        $this->assertTrue($result->isSuccessful());
    }

    public function testVersionBumpForcesUpdateInCreateMode(): void
    {
        // A declared, newer per-row version forces an update of an existing
        // rewrite even in create mode (see ReconciliationGate::decide). The
        // version is read from the CSV `version` column, forwarded to the gate,
        // and committed after a successful save.
        $versionManagement = $this->createMock(VersionManagementInterface::class);
        $versionManagement->method('isNewVersion')->willReturn(true);
        $gate = new ReconciliationGate($versionManagement, $this->log);
        $this->component = new Rewrites(
            $this->urlPersist,
            $this->urlRewriteFactory,
            $this->urlRewriteResource,
            $this->log,
            $gate
        );

        $existing = $this->makeUrlRewriteMock($this->setterMethods());
        $existing->method('setIsAutogenerated')->willReturnSelf();
        $existing->method('setStoreId')->willReturnSelf();
        $existing->method('setRequestPath')->willReturnSelf();
        $existing->method('setTargetPath')->willReturnSelf();
        $existing->method('setRedirectType')->willReturnSelf();
        $existing->method('setDescription')->willReturnSelf();

        $rewrite = $this->givenRewriteWithCollection(1, $existing);
        $this->urlRewriteFactory->method('create')->willReturn($rewrite);

        // Version bump -> the existing rewrite is updated and persisted, then its
        // version is committed under the scope-qualified id.
        $this->urlRewriteResource->expects($this->once())->method('save')->with($existing);
        $versionManagement->expects($this->once())
            ->method('setVersion')
            ->with('rewrites_about-us_1', 5);

        $result = $this->execute([
            ['requestPath', 'targetPath', 'redirectType', 'storeId', 'description', 'version'],
            ['about-us', 'cms/page/view/page_id/2', '301', '1', 'About us redirect', '5'],
        ], false, ComponentMode::Create);

        $this->assertSame(1, $result->getUpdated());
        $this->assertSame(0, $result->getSkipped());
    }

    public function testDryRunRecordsIntentWithoutSaving(): void
    {
        $rewrite = $this->givenRewriteWithCollection(0);
        $this->urlRewriteFactory->method('create')->willReturn($rewrite);

        $this->urlRewriteResource->expects($this->never())->method('save');

        $result = $this->execute($this->sampleSource(), true);

        // Intent is recorded as a create, but nothing is persisted.
        $this->assertSame(1, $result->getCreated());
        $this->assertTrue($result->isSuccessful());
    }

    public function testRecordsErrorWhenNoRowData(): void
    {
        $this->urlRewriteFactory->expects($this->never())->method('create');
        $this->urlRewriteResource->expects($this->never())->method('save');

        // Empty data array -> $data[0] not set -> error, no processing.
        $result = $this->execute([]);

        $this->assertFalse($result->isSuccessful());
        $this->assertNotEmpty($result->getErrors());
    }

    public function testRowMissingRequestPathIsLoggedAndSkippedWithoutSaving(): void
    {
        // Header lacks the requestPath column, so no row yields a request path.
        $source = [
            ['targetPath', 'redirectType', 'storeId', 'description'],
            ['/cms/page', '301', '1', 'No request path'],
        ];

        $this->urlRewriteFactory->expects($this->never())->method('create');
        $this->urlRewriteResource->expects($this->never())->method('save');
        $this->log->expects($this->atLeastOnce())
            ->method('logError')
            ->with(Rewrites::URL_REWRITE_REQUIRES_A_REQUEST_PATH_TO_BE_SET_MESSAGE);

        $result = $this->execute($source);

        // The row is skipped silently (logged only); the run itself stays successful.
        $this->assertTrue($result->isSuccessful());
        $this->assertSame(0, $result->getCreated());
        $this->assertSame(0, $result->getUpdated());
    }

    public function testExportFullDumpsEveryNonAutogeneratedRewrite(): void
    {
        $rewrite = $this->givenRewriteRecord([
            'request_path' => 'about-us',
            'target_path' => 'cms/page/view/page_id/2',
            'redirect_type' => '301',
            'store_id' => '1',
            'description' => 'About us redirect',
        ]);
        $this->givenExportCollection([$rewrite]);

        $out = $this->component->export(new ExportContext([], true));

        // Header row first, then one data row per rewrite.
        $this->assertCount(2, $out);
        $this->assertSame(
            ['requestPath', 'targetPath', 'redirectType', 'storeId', 'description'],
            $out[0]
        );
        $row = array_combine($out[0], $out[1]);
        $this->assertSame('about-us', $row['requestPath']);
        $this->assertSame('cms/page/view/page_id/2', $row['targetPath']);
        $this->assertSame('301', $row['redirectType']);
        $this->assertSame('1', $row['storeId']);
        $this->assertSame('About us redirect', $row['description']);
    }

    public function testExportFullAppliesRequestPathFilter(): void
    {
        $collection = $this->createMock(Collection::class);
        $collection->method('getIterator')->willReturn(new \ArrayIterator([]));
        // First filter pins to non-autogenerated rows; the filter prefix is a LIKE clause.
        $collection->expects($this->exactly(2))
            ->method('addFieldToFilter')
            ->willReturnSelf();
        $this->urlRewriteFactory->method('create')->willReturn($this->wrapCollection($collection));

        $out = $this->component->export(new ExportContext([], true, 'about'));

        // Only the header row survives an empty filtered collection.
        $this->assertCount(1, $out);
        $this->assertSame(
            ['requestPath', 'targetPath', 'redirectType', 'storeId', 'description'],
            $out[0]
        );
    }

    public function testExportRefreshRebuildsOnlyTrackedRewrites(): void
    {
        $existing = [
            ['requestPath', 'targetPath', 'redirectType', 'storeId', 'description'],
            ['about-us', 'cms/page/view/page_id/2', '301', '1', 'About'],
            ['gone', 'cms/page/view/page_id/9', '301', '1', 'Removed'],
        ];

        // Only about-us still exists in the DB, with a refreshed target.
        $rewrite = $this->givenRewriteRecord([
            'request_path' => 'about-us',
            'target_path' => 'cms/page/view/page_id/22',
            'redirect_type' => '302',
            'store_id' => '1',
            'description' => 'About refreshed',
            'id' => 7,
        ]);
        // First loadRewrite() returns the live record; second returns an empty (id 0) one.
        $missing = $this->givenRewriteRecord(['id' => 0]);
        $this->givenLoadResults([$rewrite, $missing]);

        $out = $this->component->export(new ExportContext($existing, false));

        $this->assertSame($existing[0], $out[0]);
        // Tracked + present -> rebuilt from current DB values, in the file's column order.
        $tracked = array_combine($out[0], $out[1]);
        $this->assertSame('about-us', $tracked['requestPath']);
        $this->assertSame('cms/page/view/page_id/22', $tracked['targetPath']);
        $this->assertSame('302', $tracked['redirectType']);
        $this->assertSame('About refreshed', $tracked['description']);
        // Tracked but no longer in the DB -> existing row preserved untouched.
        $this->assertSame(['gone', 'cms/page/view/page_id/9', '301', '1', 'Removed'], $out[2]);
    }

    public function testExportRefreshReturnsExistingWhenNoHeader(): void
    {
        $this->urlRewriteFactory->expects($this->never())->method('create');

        // No header row -> nothing to refresh, return the input verbatim.
        $out = $this->component->export(new ExportContext([], false));

        $this->assertSame([], $out);
    }

    /**
     * @param array $rows full source override (list of rows, index 0 is the header)
     */
    private function execute(
        array $rows,
        bool $dryRun = false,
        ComponentMode $mode = ComponentMode::Create,
        ?int $version = null
    ): ComponentResult {
        $context = new ComponentContext(
            'test.yaml',
            $mode,
            'test',
            $dryRun,
            static fn (): array => $rows,
            $version
        );

        return $this->component->execute($context);
    }

    /**
     * A minimal two-row source (header + one rewrite).
     *
     * @return array
     */
    private function sampleSource(): array
    {
        return [
            ['requestPath', 'targetPath', 'redirectType', 'storeId', 'description'],
            ['about-us', 'cms/page/view/page_id/2', '301', '1', 'About us redirect'],
        ];
    }

    /**
     * Build a UrlRewrite mock. UrlRewrite exposes its request/target/store/etc
     * accessors as Magento magic methods (data-model backed), so they are not
     * declared on the class and must be wired via addMethods(); getCollection()
     * and getId() are real declared methods on AbstractModel.
     *
     * @param string[] $magicMethods
     */
    private function makeUrlRewriteMock(array $magicMethods = []): UrlRewrite&MockObject
    {
        return $this->getMockBuilder(UrlRewrite::class)
            ->disableOriginalConstructor()
            ->onlyMethods(['getCollection', 'getId'])
            ->addMethods($magicMethods)
            ->getMock();
    }

    /**
     * The set of magic setter methods used on the create/update path.
     *
     * @return string[]
     */
    private function setterMethods(): array
    {
        return [
            'setIsAutogenerated',
            'setStoreId',
            'setRequestPath',
            'setTargetPath',
            'setRedirectType',
            'setDescription',
        ];
    }

    /**
     * The set of magic getter methods used when building an export row.
     *
     * @return string[]
     */
    private function getterMethods(): array
    {
        return [
            'getRequestPath',
            'getTargetPath',
            'getRedirectType',
            'getStoreId',
            'getDescription',
        ];
    }

    /**
     * Build the UrlRewrite model the factory returns during execute(). Its
     * getCollection() answers addFieldToFilter() fluently, reports the given size
     * and (for the update path) yields $firstItem from getFirstItem().
     */
    private function givenRewriteWithCollection(int $size, ?UrlRewrite $firstItem = null): UrlRewrite&MockObject
    {
        $collection = $this->createMock(Collection::class);
        $collection->method('addFieldToFilter')->willReturnSelf();
        $collection->method('getSize')->willReturn($size);
        $collection->method('getFirstItem')->willReturn($firstItem ?? $this->makeUrlRewriteMock($this->setterMethods()));

        $rewrite = $this->makeUrlRewriteMock($this->setterMethods());
        $rewrite->method('getCollection')->willReturn($collection);

        return $rewrite;
    }

    /**
     * A UrlRewrite record exposing the getter values used when building an export row.
     *
     * @param array<string, mixed> $values
     */
    private function givenRewriteRecord(array $values): UrlRewrite&MockObject
    {
        $rewrite = $this->makeUrlRewriteMock($this->getterMethods());
        $rewrite->method('getRequestPath')->willReturn($values['request_path'] ?? '');
        $rewrite->method('getTargetPath')->willReturn($values['target_path'] ?? '');
        $rewrite->method('getRedirectType')->willReturn($values['redirect_type'] ?? '');
        $rewrite->method('getStoreId')->willReturn($values['store_id'] ?? '');
        $rewrite->method('getDescription')->willReturn($values['description'] ?? '');
        $rewrite->method('getId')->willReturn($values['id'] ?? null);

        return $rewrite;
    }

    /**
     * Wire the factory so a full export iterates the given rewrites.
     *
     * @param array $rewrites
     */
    private function givenExportCollection(array $rewrites): void
    {
        $collection = $this->createMock(Collection::class);
        $collection->method('getIterator')->willReturn(new \ArrayIterator($rewrites));
        $collection->method('addFieldToFilter')->willReturnSelf();
        $this->urlRewriteFactory->method('create')->willReturn($this->wrapCollection($collection));
    }

    /**
     * Wire the factory so each loadRewrite() call (one collection per call) returns
     * the next record's getFirstItem() in sequence.
     *
     * @param UrlRewrite[] $records
     */
    private function givenLoadResults(array $records): void
    {
        $wrappers = [];
        foreach ($records as $record) {
            $collection = $this->createMock(Collection::class);
            $collection->method('addFieldToFilter')->willReturnSelf();
            $collection->method('getFirstItem')->willReturn($record);
            $wrappers[] = $this->wrapCollection($collection);
        }

        $this->urlRewriteFactory->method('create')->willReturn(...$wrappers);
    }

    /**
     * The component calls $this->urlRewriteFactory->create()->getCollection(); wrap
     * the collection in a UrlRewrite model whose getCollection() returns it.
     */
    private function wrapCollection(Collection&MockObject $collection): UrlRewrite&MockObject
    {
        $rewrite = $this->createMock(UrlRewrite::class);
        $rewrite->method('getCollection')->willReturn($collection);

        return $rewrite;
    }
}
